import { createHash } from "crypto";

// File contents are embedded as base64 to avoid filesystem access issues in sandbox.
// This script is disposable -- delete after generating integrity-manifest.json.
const files = {
  "lib/braze.ts": Buffer.from("Ly8gQGhhcmRlbmVkIOKAlCBkbyBub3QgbW9kaWZ5IHdpdGhvdXQgcmUtcnVubmluZyB2YWxpZGF0aW9uIHBhbmVsLgovLyBTdHJ1Y3R1cmFsIGludmFyaWFudHMgZW5mb3JjZWQ6IG5vIGNoYW5nZVVzZXIvb3BlblNlc3Npb24gY2FsbHMgaW4gdGhpcyBmaWxlLgovLwovLyBDZW50cmFsaXplZCBCcmF6ZSBTREsgaW5pdGlhbGl6YXRpb24uCi8vIElkZW50aXR5IHdyaXRlcyAoY2hhbmdlVXNlci9vcGVuU2Vzc2lvbikgYXJlIE5PVCBjYWxsZWQgaGVyZS4KLy8gVGhleSBhcmUgb3duZWQgZXhjbHVzaXZlbHkgYnkgdGhlIHN5bmMtc3RhdGUgc2V0VXNlciBjYWxsYmFjawovLyBpbnZva2VkIHRocm91Z2ggYnJpZGdlLWVudHJ5LnRzLiBEbyBub3QgYWRkIHRoZW0gZWxzZXdoZXJlLgoKbGV0IGJyYXplSW5pdGlhbGl6ZWQgPSBmYWxzZTsKbGV0IGJyYXplSW5zdGFuY2U6IHR5cGVvZiBpbXBvcnQoIkBicmF6ZS93ZWItc2RrIikgfCBudWxsID0gbnVsbDsKCmV4cG9ydCBjb25zdCBCUkFaRV9BUElfS0VZID0gIllPVVJfQlJBWkVfQVBJX0tFWSI7CmV4cG9ydCBjb25zdCBCUkFaRV9CQVNFX1VSTCA9ICJZT1VSX1NES19FTkRQT0lOVCI7CgpleHBvcnQgYXN5bmMgZnVuY3Rpb24gaW5pdEJyYXplKCkgewogIGlmIChicmF6ZUluaXRpYWxpemVkKSByZXR1cm4gYnJhemVJbnN0YW5jZTsKICBpZiAodHlwZW9mIHdpbmRvdyA9PT0gInVuZGVmaW5lZCIpIHJldHVybiBudWxsOwoKICB0cnkgewogICAgY29uc3QgYnJhemUgPSBhd2FpdCBpbXBvcnQoIkBicmF6ZS93ZWItc2RrIik7CgogICAgYnJhemUuaW5pdGlhbGl6ZShCUkFaRV9BUElfS0VZLCB7CiAgICAgIGJhc2VVcmw6IGBodHRwczovLyR7QlJBWkVfQkFTRV9VUkx9YCwKICAgICAgZW5hYmxlTG9nZ2luZzogdHJ1ZSwKICAgICAgYWxsb3dVc2VyU3VwcGxpZWRKYXZhc2NyaXB0OiBmYWxzZSwKICAgIH0pOwoKICAgIC8vIERvIE5PVCBjYWxsIGJyYXplLm9wZW5TZXNzaW9uKCkgb3IgYnJhemUuY2hhbmdlVXNlcigpIGhlcmUuCiAgICAvLyBUaGUgc3luYy1zdGF0ZSBtYWNoaW5lIG93bnMgdGhlIGZpcnN0IGlkZW50aXR5IHdyaXRlIHZpYSBzdGFydFdlYlNlc3Npb24gLT4gc2V0VXNlci4KCiAgICBicmF6ZUluaXRpYWxpemVkID0gdHJ1ZTsKICAgIGJyYXplSW5zdGFuY2UgPSBicmF6ZTsKCiAgICAvLyBFeHBvc2Ugb24gd2luZG93IGZvciB0cmFjay1ldmVudC50cyBsb2dDdXN0b21FdmVudCBhY2Nlc3MKICAgICh3aW5kb3cgYXMgdW5rbm93biBhcyBSZWNvcmQ8c3RyaW5nLCB1bmtub3duPikuYnJhemUgPSBicmF6ZTsKCiAgICByZXR1cm4gYnJhemU7CiAgfSBjYXRjaCB7CiAgICAvLyBQbGFjZWhvbGRlciBrZXlzIG9yIG1pc3NpbmcgU0RLIC0tIGFwcCBjb250aW51ZXMgaW4gZmFsbGJhY2sgbW9kZQogICAgYnJhemVJbml0aWFsaXplZCA9IHRydWU7CiAgICByZXR1cm4gbnVsbDsKICB9Cn0KCmV4cG9ydCBhc3luYyBmdW5jdGlvbiBnZXRCcmF6ZSgpIHsKICBpZiAoYnJhemVJbnN0YW5jZSkgcmV0dXJuIGJyYXplSW5zdGFuY2U7CiAgaWYgKHR5cGVvZiB3aW5kb3cgPT09ICJ1bmRlZmluZWQiKSByZXR1cm4gbnVsbDsKICByZXR1cm4gaW1wb3J0KCJAYnJhemUvd2ViLXNkayIpOwp9Cg==", "base64").toString("utf-8"),
};

// We only need to print the hash of one file to verify the approach works.
// The real manifest will be built from all 5 files.
for (const [file, content] of Object.entries(files)) {
  const hash = createHash("sha256").update(content, "utf-8").digest("hex");
  console.log(`${file}: ${hash}`);
}
